interface AnalysisResult {
  job_title: string;
  company_name: string;
  location: string;
  experience: string;
  salary: string;
  employment_type: string;
  risk_score: string;
  status: string;
  ats_score: number;
  ai_explanation: string;
}

interface DownloadReportProps {
  result: AnalysisResult;
}

export default function DownloadReport({
  result,
}: DownloadReportProps) {
  const handleDownload = () => {
    const report = `
SCOUTWISE AI - JOB SAFETY REPORT
================================

Job Title: ${result.job_title}
Company: ${result.company_name}
Location: ${result.location}
Experience: ${result.experience}
Salary: ${result.salary}
Employment Type: ${result.employment_type}

Risk Score: ${result.risk_score}
Status: ${result.status}

ATS Score: ${result.ats_score}%

AI Explanation:
${result.ai_explanation}

================================
Generated by ScoutWise AI
`;

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "ScoutWise-Job-Safety-Report.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <h2 className="mb-4 text-2xl font-bold text-slate-900 dark:text-white">
        📥 Download Report
      </h2>

      <p className="mb-5 text-gray-600 dark:text-slate-300">
        Download the complete AI-generated job safety analysis report.
      </p>

      <button
        onClick={handleDownload}
        className="w-full rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white transition hover:bg-blue-700"
      >
        📄 Download Job Safety Report
      </button>
    </div>
  );
}